#!/bin/sh
#
# Description: 
#
# Authors:      Qin Guanri
#
# Copyright:    2016 403709339@qq.com
# License:      
#
###############################################################################
# Global:
WORK_DIR=$(cd `dirname $0`; cd ../; pwd)
PCMK_RPM_TAR="yum_pacemaker.tar"
IPTABLES_RPM_TAR="yum_iptables.tar"
DRBD_RPM_TAR="yum_drbd.tar"
NFS_RPM_TAR="yum_nfs.tar"

losetup_dev_default=/dev/loop9


check_ip_valid() {
    echo $1|grep "^[0-9]\{1,3\}\.\([0-9]\{1,3\}\.\)\{2\}[0-9]\{1,3\}$" > /dev/null; 
    if [ $? -ne 0 ]; then 
        return 1 
    fi
    ipaddr=$1 
    a=`echo $ipaddr|awk -F . '{print $1}'`  #以"."分隔，取出每个列的值 
    b=`echo $ipaddr|awk -F . '{print $2}'` 
    c=`echo $ipaddr|awk -F . '{print $3}'` 
    d=`echo $ipaddr|awk -F . '{print $4}'` 
    for num in $a $b $c $d 
    do
        if [ $num -gt 255 ] || [ $num -lt 0 ]; then 
            return 1 
        fi 
    done
    return 0
}

check_repo() {
    repo_list=$@
    for item in ${repo_list[@]}
    do
        ls -lh /etc/yum.repos.d/"$item"
        if [ $? -ne 0 ]; then
            return 1
        fi
    done

    return 0
}

create_repo() {
    check_repo "CentOS-Pacemaker.repo"
    if [ $? -eq 0 ]; then
        return 0
    fi

    # create repo for pacemaker
    if [ ! -f $WORK_DIR/dependent/$PCMK_RPM_TAR ]; then
        echo "ERROR. No such file or directory:$WORK_DIR/dependent/$PCMK_RPM_TAR"
        return 1
    fi
    cp $WORK_DIR/dependent/$PCMK_RPM_TAR /
    cd /

    tar xvmf "$PCMK_RPM_TAR"
    rm -f $PCMK_RPM_TAR

    echo "[Pacemaker]
name=Pacemaker Yum
baseurl=file:///yum_pacemaker/
gpgcheck=0
enabled=1" > /etc/yum.repos.d/CentOS-Pacemaker.repo
    
    if [ $? -ne 0 ]; then
        echo "ERROR. create repo for pacemaker failed."
        return 1
    fi

    # create repo for iptables
    if [ ! -f $WORK_DIR/dependent/$IPTABLES_RPM_TAR ]; then
        echo "ERROR. No such file or directory:$WORK_DIR/dependent/$IPTABLES_RPM_TAR"
        return 1
    fi
    cp $WORK_DIR/dependent/$IPTABLES_RPM_TAR /
    cd /

    tar xvmf "$IPTABLES_RPM_TAR"
    rm -f $IPTABLES_RPM_TAR

    echo "[Iptables]
name=Iptables Yum
baseurl=file:///yum_iptables/
gpgcheck=0
enabled=1" > /etc/yum.repos.d/CentOS-Iptables.repo
    

    # create repo for drbd
    if [ ! -f $WORK_DIR/dependent/$DRBD_RPM_TAR ]; then
        echo "ERROR. No such file or directory:$WORK_DIR/dependent/$DRBD_RPM_TAR"
        return 1
    fi
    cp $WORK_DIR/dependent/$DRBD_RPM_TAR /
    cd /
    tar xvmf "$DRBD_RPM_TAR"
    rm -f $DRBD_RPM_TAR

    echo "[Drbd]
name=Drbd Yum
baseurl=file:///yum_drbd/
gpgcheck=0
enabled=1" > /etc/yum.repos.d/CentOS-Drbd.repo

    # create repo for nfs
    if [ ! -f $WORK_DIR/dependent/$NFS_RPM_TAR ]; then
        echo "ERROR. No such file or directory:$WORK_DIR/dependent/$NFS_RPM_TAR"
        return 1
    fi
    cp $WORK_DIR/dependent/$NFS_RPM_TAR /
    cd /
    tar xvmf "$NFS_RPM_TAR"
    rm -f $NFS_RPM_TAR

    echo "[Nfs]
name=Nfs Yum
baseurl=file:///yum_nfs/
gpgcheck=0
enabled=1" > /etc/yum.repos.d/CentOS-Nfs.repo

    return 0
}


check_args_valid() {
    source $WORK_DIR/conf/ha.conf
    [ $? -ne 0 ] && return 1

    ping -c 1 "$master_ip"
    if [ $? -ne 0 ]; then
        echo "ERROR. ping $master_ip failed"
        return 1
    fi

    ping -c 1 "$slave_ip"
    if [ $? -ne 0 ]; then
        echo "ERROR. ping $slave_ip failed"
        return 1
    fi

    if ! check_ip_valid "$vip_master"; then
        echo "ERROR. vip_master is not valid"
        return 1
    fi

    if [ ! -n "$master_hostname" ] || [ ! -n "$slave_hostname" ] ||
       [ ! -n "$data_dir" ]; then
        echo "ERROR. some param is null"
        return 1
    fi

    if [ ! -n "$drbd_size" ]; then
        echo "drbd_size=1000" >> $WORK_DIR/conf/ha.conf
    fi

    if [ $drbd_size -lt 1 ] || [ $drbd_size -gt 500000 ]; then
        echo "param drbd_size=$drbd_size is invalid."
        return 1
    fi

    if [ ! -n "$losetup_dev" ] || [ "$losetup_dev" == "" ]; then
        echo "WARN. losetup_dev is null.use default: $losetup_dev_default"
        echo "losetup_dev=$losetup_dev_default" >> $WORK_DIR/conf/ha.conf
    fi

    return 0
}

check_install() {
    soft_list=$@
    for item in ${soft_list[@]}
    do
        installed=`yum list installed | grep "$item" |grep -v grep | wc -l`
        if [ "$installed" == "0" ]; then
            return 1
        fi
    done

    return 0
}

# execute function
$@
